package com.oexil.univote.enums;

public enum SettingKey {
    STUDENT_DEFAULT_SUBSCRIPTION_FEE,
    STUDENT_DEFAULT_SUBCLASS_SUBSCRIPTION_FEE,
    INSTRUCTOR_DEFAULT_SUBSCRIPTION_FEE,

    INCOME_DEFAULT_SUBSCRIPTION_FEE,
}
